"""
Authentication dependencies for FastAPI.
"""
import os
from typing import Optional
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import jwt, JWTError
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.models import User
from dotenv import load_dotenv

load_dotenv()

security = HTTPBearer()

JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', 'your-jwt-secret-key-here-change-in-production')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')


def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    db: Session = Depends(get_db)
) -> User:
    """
    Validate JWT token and return current user.
    Token is generated by Django SimpleJWT.
    """
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    
    try:
        token = credentials.credentials
        payload = jwt.decode(token, JWT_SECRET_KEY, algorithms=[JWT_ALGORITHM])
        user_id: int = payload.get("user_id")
        if user_id is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception
    
    user = db.query(User).filter(User.id == user_id).first()
    if user is None:
        raise credentials_exception
    
    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User account is inactive"
        )
    
    return user


def require_role(*allowed_roles: str):
    """
    Dependency factory to check if user has required role.
    Usage: require_role("Customer", "Admin")
    """
    def role_checker(current_user: User = Depends(get_current_user)) -> User:
        if current_user.role not in allowed_roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Access forbidden. Required role: {', '.join(allowed_roles)}"
            )
        return current_user
    return role_checker


# Pre-defined role dependencies
def get_admin_user(current_user: User = Depends(get_current_user)) -> User:
    """Dependency to get admin user."""
    if current_user.role != "Admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required"
        )
    return current_user


def get_customer_user(current_user: User = Depends(get_current_user)) -> User:
    """Dependency to get customer user."""
    if current_user.role != "Customer":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Customer access required"
        )
    return current_user


def get_restaurant_owner_user(current_user: User = Depends(get_current_user)) -> User:
    """Dependency to get restaurant owner user."""
    if current_user.role != "Restaurant Owner":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Restaurant Owner access required"
        )
    return current_user


def get_delivery_partner_user(current_user: User = Depends(get_current_user)) -> User:
    """Dependency to get delivery partner user."""
    if current_user.role != "Delivery Partner":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Delivery Partner access required"
        )
    return current_user


def get_customer_care_user(current_user: User = Depends(get_current_user)) -> User:
    """Dependency to get customer care user."""
    if current_user.role != "Customer Care":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Customer Care access required"
        )
    return current_user
